config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :users, :only => [:show]
  resources :spaces do
    resources :photos, :except => [:show, :index, :edit, :update]
    resources :bookings, :except => [:index, :edit, :update]
  end




end

app/models/booking.rb
class Booking<ActiveRecord::Base
  belongs_to :user
  belongs_to :space
  validates :start_date, presence: true
  validates :end_date, presence: true

  def total_cost
    self.space.cost * (self.end_date - self.start_date)
  end
end

app/models/photo.rb
class Photo<ActiveRecord::Base
  belongs_to :space

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  # validates_with AttachmentPresenceValidator, :attributes => :image
  # validates_with AttachmentSizeValidator, :attributes => :image, :less_than => 1.megabytes
  # validates_attachment :image, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }
end

app/models/space.rb
class Space<ActiveRecord::Base
  belongs_to :user
  has_many :photos
  validates :address, presence: true
  validates :cost, presence: true
  validates :description, presence: true

  has_many :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :spaces
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # helper_method :current_user
  #
  #
  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
end

app/controllers/bookings_controller.rb
class BookingsController<ApplicationController
  def new
    @booking = Booking.new
    @space = Space.find(params[:space_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.space = Space.find(params[:space_id])
    if @booking.save
      flash[:notice] = "Your reservation was successful."
      redirect_to :back
    else
      flash[:alert] = "There were problems with your reservation."
      redirect_to :back
    end
  end

  def destroy

  end

private
  def booking_params
      params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/photos_controller.rb
class PhotosController<ApplicationController
  def new
    @space = Space.find(params[:space_id])
    @photo = Photo.new
  end

  def create
    @space = Space.find(params[:space_id])
    if params[:photo] == nil
      flash[:alert] = "Try Again"
      redirect_to :back
    else
      @photo = Photo.new(photo_params)
      @photo.space_id = @space.id
      if @photo.save
        flash[:notice] = "Photo Uploaded"
        redirect_to :back
      else
        flash[:alert] = "Try Again"
        redirect_to :back
      end
    end

  end

  def destroy
    photo = Photo.find(params[:id])
    if photo.destroy
      flash[:notice] = "Photo removed"
    else
      flash[:alert] = "Something went wrong."
    end
    redirect_to :back
  end

  private
    def photo_params
        params.require(:photo).permit(:image)
    end

end

app/controllers/spaces_controller.rb
class SpacesController<ApplicationController
  def index
    @spaces = Space.all
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    if @space.save
      flash[:notice] = "Successfully created your space."
      redirect_to space_path(@space)
    else
      flash[:alert] = "There were problems with your space. Try again."
      redirect_to :back
    end
  end

  def show
    @space = Space.find(params[:id])
  end

private
  def space_params
    params.require(:space).permit(:address,:description,:cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show

  end


  #
  # private
  # def user_params
  #   params.require(:user).permit(:email, :password, :password_confirmation)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="row">

  <div class="col-sm-3"></div>

  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if current_user %>
          <h3>Reserve <%= @space.address %></h3>
          <div class="col-sm-5">
            <%= bootstrap_form_for [@space,@booking] do |f| %>
              <%= f.date_field :start_date %>
              <%= f.date_field :end_date %>
              <%= f.submit "Reserve", class: "btn btn-warning" %>
            <% end %>
          </div>
          <div class="col-sm-2"></div>
          <div class="col-sm-5">
            <% if @space.photos.any? %>
              <%= image_tag @space.photos.first.image.url(:thumb), class: "img-booking" %>
            <% end %>
          </div>
        <% else %>
          <h3>
            <%= link_to "Create A SleepOver Account to Make A Reservation", new_user_registration_path, class: "text-warning" %>
          </h3>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-3"></div>

</div>

app/views/home/index.html.erb
<body class="home-page">
  <div class="jumbotron front-well">
    <h1>SleepOver</h1>
    <h2><small>Let us help you find your dream getaway.</small></h2>
    <hr>
    <%= link_to "Register Now", new_user_registration_path, class: "btn btn-success btn-lg" %>
  </div>
</body>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/spaces">SleepOver</a>
    </div>

    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
          Browse <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Create Listing', new_space_path %></li>
          <li><%= link_to 'View All Listings', spaces_path %></li>
        </ul>
      </li>
    </ul>

    <div class="navbar-right our-right-nav">

      <% if user_signed_in? %>

          <%= current_user.email %>
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete , class: 'btn btn-info' %>
          <%= link_to 'My Stuff', user_path(current_user) , class: 'btn btn-primary' %>
      <% else %>
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SleepOver</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="background">
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/photos/new.html.erb
<h4>Add Photo</h4>

<%= bootstrap_form_for [@space, @photo], :html => { :multipart => true } do |f| %>
  <%= f.file_field :image, class: "btn btn-sm" %>
  <%= f.submit 'Add Photo', class: "btn btn-sm btn-success add-photo-btn" %>
<% end %>



<% @space.photos.each do |photo|%>
  <%= image_tag photo.image.url(:thumb) %>
  <%= link_to "Delete", space_photo_path(@space,photo), method: :delete %>
<% end %>


<%= link_to "Done", space_path(@space), class: "btn btn-info photo-btn-done"%>

app/views/spaces/index.html.erb
<% @spaces.each do |space| %>
  <div class="row">

    <div class="col-sm-2"></div>

    <div class="col-sm-8">
      <%= link_to space_path(space) do %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title "><%= space.address %><span class="pull-right"><%=  space.user.email %></span></h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-7">
              <h3>Description:</h3>
              <p><%= space.description %></p>
              <h3>$ <%= space.cost%> /night </h3>
            </div>
            <div class="col-sm-5">
              <% if space.photos.first %>
                <%= image_tag space.photos.first.image.url, class: "img-responsive img-rounded" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <% end %>

    </div>

    <div class="col-sm-2"></div>

  </div>
<% end %>

app/views/spaces/new.html.erb
<% if current_user %>

  <h3>Add Listing</h3>

  <%= bootstrap_form_for @space do |f| %>
    <%= f.text_field :address %>
    <%= f.text_field :description %>
    <%= f.text_field :cost %>
    <%= f.submit 'Add Space' %>
  <% end %>

<% else %>

  <h3><%= link_to "Create A SleepOver Account to Add Space", new_user_registration_path, class: "text-warning" %></h3>

<% end %>

app/views/spaces/show.html.erb
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-10">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title "><%= @space.address %><span class="pull-right"><%= @space.user.email %></span></h3>
      </div>
      <div class="panel-body">
        <h3>Description:</h3>
        <p><%= @space.description %></p>
        <h3>$ <%= @space.cost%> /night </h3>
        <% if @space.user == current_user%>
          <%= link_to 'Add Photos', new_space_photo_path(@space), class: "btn btn-primary add-photo-btn" %>
        <% else%>
          <%= link_to 'Make a reservation', new_space_booking_path(@space), class: "btn btn-primary add-photo-btn" %>
        <%end%>
        <% @space.photos.each do |photo| %>
          <%= image_tag photo.image.url , class: "img-responsive img-rounded img-list"%>
        <% end %>
      </div>


    </div>
  </div>
  <div class="col-sm-1"></div>
</div>

app/views/users/show.html.erb
<h2><%= current_user.email %></h2>

<% if current_user.spaces.any? %>
  <div class="row">

    <div class="col-sm-2"></div>

    <div class="col-sm-10">
      <h3><span class="text-primary">Listings</span></h3>
      <ul class="list-group">
        <% current_user.spaces.each do |space| %>
          <%= link_to space_path(space) do%>
            <li class="list-group-item">
              <div class="row">
                <div class="col-sm-10">
                  <h4><%= space.address %></h4>
                </div>
                <div class="col-sm-2">
                  <% if space.photos.first %>
                    <%= image_tag space.photos.first.image.url(:thumb), class: "img-responsive img-rounded" %>
                  <% end %>
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <%= link_to "Add listing", new_space_path, class: "btn btn-default pull-right"%>
  </div>
<% else %>
    <%= link_to "Add listing", new_space_path, class: "btn btn-default pull-right"%>
<% end %>

<% if current_user.bookings.any? %>
  <div class="row">

    <div class="col-sm-2"></div>

    <div class="col-sm-10">
      <h3><span class="text-primary">Bookings</span></h3>
      <ul class="list-group">
        <% current_user.bookings.each do |booking| %>
          <li class="list-group-item">
            <div class="row">
              <div class="col-sm-10">
                <h4><%= booking.space.address %></h4>
              </div>
              <div class="col-sm-2">
                <% if booking.space.photos.first %>
                  <%= image_tag booking.space.photos.first.image.url(:thumb), class: "img-responsive img-rounded" %>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>